name: Android CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Run Android Lint
        run: ./gradlew lint

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: app/build/reports/lint-results-debug.html
      - name: Generate JaCoCo Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport/html/
